using System.Reflection;
using System.Text.Json;

namespace GameArt.Tests;

/// <summary>
/// U9 (asset completion wave, R9): "every live asset is regenerable, or explicitly recorded as
/// unreproducible" as a real assertion over the committed manifest, not a claim in prose
/// (`docs/design/ASSETS.md` §6 "Provenance gaps" / §8 to-do #9).
///
/// <para><b>Why this file reads the filesystem, unlike every other test in this project.</b> This
/// project's own header comment describes the fast lane as "NO Godot, NO filesystem/pixel IO"
/// (KTD3) — but that guarantee is about PIXEL IO specifically: decoding/hashing a PNG's bytes is
/// the LOCK GATE's job, a separate CI step per `docs/design/art-pipeline-architecture.md` §"Lock
/// gate", never this fast lane's. Reading two small JSON/text manifests (never a PNG) to check that
/// every committed art id has a provenance disposition is a different, lighter thing, and
/// `sim/GameSim.Tests/ConstitutionTests.cs`'s own `RepoRoot()` — walking up from the test
/// assembly's location to find `Game.sln` — is already exactly this pattern, alive today in the
/// fast lane this repo actually runs. This file copies it rather than inventing a second one.</para>
/// </summary>
public class AssetProvenanceTests
{
    private static string RepoRoot()
    {
        var dir = new DirectoryInfo(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)!);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "Game.sln")))
        {
            dir = dir.Parent;
        }

        Assert.True(dir is not null, "Could not find Game.sln walking up from the test assembly.");
        return dir!.FullName;
    }

    private static IReadOnlyList<string> ManifestIds()
    {
        var path = Path.Combine(RepoRoot(), "godot", "assets", "art", "art-manifest.json");
        using var doc = JsonDocument.Parse(File.ReadAllText(path));
        return doc.RootElement.EnumerateObject().Select(p => p.Name).ToList();
    }

    private static IReadOnlySet<string> BuildJsonIds()
    {
        var dir = Path.Combine(RepoRoot(), "art", "build");
        const string suffix = ".build.json";
        return Directory.EnumerateFiles(dir, "*" + suffix)
            .Select(f => Path.GetFileName(f))
            .Select(f => f[..^suffix.Length])
            .ToHashSet(StringComparer.Ordinal);
    }

    /// <summary>
    /// U9's documented exception list for manifest ids that carry no <c>art/build/*.build.json</c>
    /// and have no generator either — every entry below was individually traced to a "no script, no
    /// seed, nothing to re-run" conclusion during U9, not assumed. Two shapes:
    /// <c>forge</c>/<c>noticeboard</c> are the same pre-pipeline SDXL-era gap as the sibling
    /// <c>market</c>/<c>tavern</c>/<c>mine-gate</c> ids U9 DID backfill (see their
    /// <c>art/build/*.build.json</c> <c>"unreproducible-legacy"</c> records for the pattern);
    /// <c>panel_banner_*</c>/<c>ui-frame-wood</c> never had a build-half to begin with (see
    /// <c>godot/assets/art/README.md</c>'s own "Ids outside the AssetSpec grammar" section for
    /// <c>panel_banner_*</c> specifically).
    /// </summary>
    private static readonly string[] DocumentedUnreproducibleIds =
    {
        "forge",
        "noticeboard",
        "panel_banner_bounties",
        "panel_banner_heroes",
        "panel_banner_shop",
        "panel_banner_tavern",
        "ui-frame-wood",
    };

    /// <summary>
    /// Ids with no <c>art/build/*.build.json</c> that ARE regenerable via a committed, deterministic
    /// script — the "script itself IS the provenance" convention `godot/assets/art/README.md`
    /// documents for the hand-authored pixel track. <c>player_smith*</c> sits outside the
    /// `AssetSpec` id grammar (README's own U9 section) but is otherwise exactly this: it is
    /// produced by the same `tools/art/gen_town_sprites.py` `all_sprites` map and `main()` write
    /// loop as every `town2d-hero-*` body. <c>item-rival-{weapon,shield,armor}</c> is generated by
    /// `art/pipeline/gen-rival-icons.py` (its own `--check` drift guard), a kebab-case id that
    /// simply predates this repo's `art/build/` convention.
    /// </summary>
    private static readonly string[] HandAuthoredExactIds =
    {
        "player_smith",
        "player_smith_step",
        "player_smith_walk2",
        "player_smith_walk4",
        "item-rival-weapon",
        "item-rival-shield",
        "item-rival-armor",
    };

    /// <summary>Every <c>town2d-</c> id is the hand-authored pixel track: some come from
    /// <c>tools/art/gen_town_sprites.py</c> (hero/townsfolk bodies), the rest from a dedicated
    /// <c>art/pipeline/gen-*.py</c> script (market/signs/interiors/ground tiles) — each individually
    /// traced to its generator during U9. None carries (or needs) an <c>art/build/*.build.json</c>;
    /// the script IS the provenance, per this project's own README.</summary>
    private const string HandAuthoredPrefix = "town2d-";

    [Fact]
    public void EveryManifestId_HasBuildJson_OrIsARecognizedException()
    {
        var manifestIds = ManifestIds();
        var buildIds = BuildJsonIds();
        var documented = DocumentedUnreproducibleIds.ToHashSet(StringComparer.Ordinal);
        var handAuthored = HandAuthoredExactIds.ToHashSet(StringComparer.Ordinal);

        var uncovered = manifestIds.Where(id =>
            !buildIds.Contains(id)
            && !documented.Contains(id)
            && !handAuthored.Contains(id)
            && !id.StartsWith(HandAuthoredPrefix, StringComparison.Ordinal)
        ).ToList();

        Assert.True(uncovered.Count == 0,
            "Manifest id(s) with no build.json, no recognized hand-authored-script coverage, and no "
            + "documented unreproducible entry. Fix by adding a real art/build/<id>.build.json, or by "
            + "adding the id (with a real reason, never a guess) to this file's DocumentedUnreproducibleIds "
            + $"or HandAuthoredExactIds: {string.Join(", ", uncovered)}");
    }

    [Fact]
    public void DocumentedUnreproducibleIds_NeverActuallyHaveABuildJson()
    {
        // If a listed id gains a build.json later (someone backfills it from a recovered seed the
        // way market/tavern/mine-gate and the five monster minis were), its entry here is stale —
        // remove it rather than let a passing test hide a now-provenanced asset from a reader.
        var buildIds = BuildJsonIds();
        var stale = DocumentedUnreproducibleIds.Where(buildIds.Contains).ToList();

        Assert.True(stale.Count == 0,
            "These ids now have a build.json -- remove them from DocumentedUnreproducibleIds: "
            + string.Join(", ", stale));
    }

    [Fact]
    public void HandAuthoredExactIds_NeverActuallyHaveABuildJson()
    {
        var buildIds = BuildJsonIds();
        var stale = HandAuthoredExactIds.Where(buildIds.Contains).ToList();

        Assert.True(stale.Count == 0,
            "These ids now have a build.json -- remove them from HandAuthoredExactIds: "
            + string.Join(", ", stale));
    }

    [Theory]
    [InlineData("market")]
    [InlineData("tavern")]
    [InlineData("mine-gate")]
    public void U9BackfilledIds_AreHonestlyMarkedUnreproducibleLegacy(string id)
    {
        var path = Path.Combine(RepoRoot(), "art", "build", $"{id}.build.json");
        using var doc = JsonDocument.Parse(File.ReadAllText(path));

        Assert.Equal("unreproducible-legacy", doc.RootElement.GetProperty("Status").GetString());
        Assert.Equal(JsonValueKind.Null, doc.RootElement.GetProperty("Seed").ValueKind);
        Assert.Equal(JsonValueKind.Null, doc.RootElement.GetProperty("Model").ValueKind);
    }

    /// <summary>
    /// The five mine monsters left the list above on 2026-08-14 (§11.10 U4): they now have a real
    /// generator, so <c>unreproducible-legacy</c> became a false claim about them and the row had to
    /// move rather than be corrected in prose (CLAUDE.md rule 8).
    ///
    /// <para>Worth recording why they were ever in that list. They had no build script of any kind
    /// and the repo never recorded their method — and measurement showed it could not have been the
    /// "Hand-pixel Python" ASSETS.md credited them to: 972 to 5,755 distinct opaque colours across
    /// the five, at sizes from 60x41 to 84x99. That is a generated image downscaled, not authored
    /// pixel art. They are now genuinely the thing the docs claimed.</para>
    /// </summary>
    [Theory]
    [InlineData("town2d-monster-cave-rat")]
    [InlineData("town2d-monster-tunnel-spider")]
    [InlineData("town2d-monster-deep-ghoul")]
    [InlineData("town2d-monster-ore-golem")]
    [InlineData("town2d-monster-forgeworm")]
    public void MineMonsters_AreProcedural_AndSayHowToReRenderThem(string id)
    {
        var path = Path.Combine(RepoRoot(), "art", "build", $"{id}.build.json");
        using var doc = JsonDocument.Parse(File.ReadAllText(path));

        Assert.Equal("procedural", doc.RootElement.GetProperty("Status").GetString());

        // A procedural record whose disclosure does not name its generator is as unhelpful as no
        // record — the point of the status flip is that someone can re-render these.
        var disclosure = doc.RootElement.GetProperty("Provenance").GetProperty("aiDisclosure").GetString();
        Assert.NotNull(disclosure);
        Assert.Contains("gen_town_sprites.py", disclosure!, StringComparison.Ordinal);
        Assert.Contains("--check", disclosure!, StringComparison.Ordinal);

        // Still no seed/model: procedural means deterministic code, not a recorded generation.
        Assert.Equal(JsonValueKind.Null, doc.RootElement.GetProperty("Seed").ValueKind);
        Assert.Equal(JsonValueKind.Null, doc.RootElement.GetProperty("Model").ValueKind);
    }

    /// <summary>
    /// The whole <c>town-*</c> family (<c>town-forge</c>, <c>town-market</c>, <c>town-mine-gate</c>,
    /// <c>town-tavern</c>) was deleted with its art in the same wave as this backfill — the LitOverlay
    /// scene that drew it is long gone. Provenance for art that no longer exists is an orphan record,
    /// so those four <c>build.json</c> files went with the PNGs. This pins the absence: a future
    /// session that re-adds one without re-adding the art is re-creating the orphan.
    /// </summary>
    [Theory]
    [InlineData("town-forge")]
    [InlineData("town-market")]
    [InlineData("town-mine-gate")]
    [InlineData("town-tavern")]
    public void DeletedTownOverlayIds_HaveNoOrphanedProvenanceRecord(string id)
    {
        var buildJson = Path.Combine(RepoRoot(), "art", "build", $"{id}.build.json");
        var art = Path.Combine(RepoRoot(), "godot", "assets", "art", $"{id}.png");

        Assert.False(File.Exists(art), $"{id}.png is back — if the art returned, its provenance should too.");
        Assert.False(File.Exists(buildJson),
            $"{id}.build.json describes art that no longer exists ({art}). Delete the record or restore the art.");
    }
}
